import sys; sys.path.insert(0, ".")
import r219_lib as L
print("== grants ipd_app@127.0.0.1 ==")
for r in L.sql("SHOW GRANTS FOR 'ipd_app'@'127.0.0.1'"): print(r)
print("== login accounts ==")
for r in L.sql("SELECT id, name, person_type, group_id, level, username, account_status FROM persons WHERE username IS NOT NULL AND username<>'' AND del_flag='0'"): print(r)
print("== groups ==")
for r in L.sql("SELECT id, name FROM product_groups LIMIT 6"): print(r)
print("== configs ==")
for r in L.sql("SELECT config_key, config_value FROM system_configs WHERE config_key LIKE 'bonus.%' OR config_key LIKE 'allowance.%' ORDER BY config_key"): print(r)
print("== ai_model_configs cols =="); print([r[0] for r in L.sql("SHOW COLUMNS FROM ai_model_configs")])
print("== ai models ==")
for r in L.sql("SELECT id, name, provider, endpoint, model, status FROM ai_model_configs"): print(r)
print("== projects ==")
for r in L.sql("SELECT id, name, level, level_coefficient, target_sales_amount, launch_date, current_stage, status, del_flag FROM projects ORDER BY id DESC LIMIT 6"): print(r)
print("== tables ==")
print([r[0] for r in L.sql("SHOW TABLES")])
