-- Work Buddy 产品线元数据。只写 catalog- 空间的 remark，不改 attendance/access-control/video，不推断旧测试产品归属。
-- 人证产品来自应建清单，不并入证卡。重复执行只在 remark 为空时写入。
INSERT INTO product_lines (id, line_code, line_name, status, tenant_id, del_flag, create_by, create_time)
SELECT 2026093000000000016, 'catalog-idcard', '人证产品', 'ACTIVE', '000000', '0', 900101, NOW()
WHERE NOT EXISTS (SELECT 1 FROM product_lines WHERE line_code='catalog-idcard' AND tenant_id='000000');
UPDATE product_lines SET remark='{"src":"workbuddy-20260909-outputs","files":8,"rows":12816,"model_mentions":12816,"unique_models":1035,"unique_customer_models":3756,"subcategories":["发卡器","巡更","访客","门禁一体机","门禁控制器","门禁梯控","门禁电锁","门禁读头"]}', update_by=900101 WHERE line_code='catalog-access' AND tenant_id='000000' AND del_flag='0' AND (remark IS NULL OR remark='');
UPDATE product_lines SET remark='{"src":"workbuddy-20260909-outputs","files":11,"rows":4259,"model_mentions":4259,"unique_models":451,"unique_customer_models":959,"subcategories":["三辊闸","伸缩门","全高闸","单摆","对开门机","平开门机","平移闸","广告门","摆闸","无障碍闸","翼闸"]}', update_by=900101 WHERE line_code='catalog-channel' AND tenant_id='000000' AND del_flag='0' AND (remark IS NULL OR remark='');
UPDATE product_lines SET remark='{"src":"workbuddy-20260909-outputs","files":12,"rows":2957,"model_mentions":2957,"unique_models":981,"unique_customer_models":1075,"subcategories":["NVR","在线会议产品","太阳能监控产品","平台服务器","显示器","智能视频盒","模拟摄像头","泛光型监控产品","热成像产品","硬盘","网络摄像头","解码器"]}', update_by=900101 WHERE line_code='catalog-video' AND tenant_id='000000' AND del_flag='0' AND (remark IS NULL OR remark='');
UPDATE product_lines SET remark='{"src":"workbuddy-20260909-outputs","files":1,"rows":1565,"model_mentions":1565,"unique_models":170,"unique_customer_models":500,"subcategories":["考勤机"]}', update_by=900101 WHERE line_code='catalog-attendance' AND tenant_id='000000' AND del_flag='0' AND (remark IS NULL OR remark='');
UPDATE product_lines SET remark='{"src":"workbuddy-20260909-outputs","files":8,"rows":730,"model_mentions":730,"unique_models":250,"unique_customer_models":454,"subcategories":["UHF","充电桩","票箱","车位引导","车位锁","车牌相机","车牌识别一体机","车牌道闸一体机"]}', update_by=900101 WHERE line_code='catalog-vehicle' AND tenant_id='000000' AND del_flag='0' AND (remark IS NULL OR remark='');
UPDATE product_lines SET remark='{"src":"workbuddy-20260909-outputs","files":6,"rows":652,"model_mentions":652,"unique_models":133,"unique_customer_models":186,"subcategories":["公寓门锁","家用门锁","挂锁","柜锁","玻璃门夹锁","酒店门锁"]}', update_by=900101 WHERE line_code='catalog-lock' AND tenant_id='000000' AND del_flag='0' AND (remark IS NULL OR remark='');
UPDATE product_lines SET remark='{"src":"workbuddy-20260909-outputs","files":3,"rows":552,"model_mentions":550,"unique_models":516,"unique_customer_models":129,"subcategories":["智慧出入口管理软件","智慧办公软件","智慧身份核验软件"]}', update_by=900101 WHERE line_code='catalog-software' AND tenant_id='000000' AND del_flag='0' AND (remark IS NULL OR remark='');
UPDATE product_lines SET remark='{"src":"workbuddy-20260909-outputs","files":3,"rows":469,"model_mentions":469,"unique_models":130,"unique_customer_models":163,"subcategories":["交换机","网关","网线"]}', update_by=900101 WHERE line_code='catalog-comms' AND tenant_id='000000' AND del_flag='0' AND (remark IS NULL OR remark='');
UPDATE product_lines SET remark='{"src":"workbuddy-20260909-outputs","files":4,"rows":443,"model_mentions":443,"unique_models":190,"unique_customer_models":197,"subcategories":["中心机","可视对讲套包","室内机","门口机"]}', update_by=900101 WHERE line_code='catalog-intercom' AND tenant_id='000000' AND del_flag='0' AND (remark IS NULL OR remark='');
UPDATE product_lines SET remark='{"src":"workbuddy-20260909-outputs","files":3,"rows":340,"model_mentions":340,"unique_models":107,"unique_customer_models":94,"subcategories":["二维码模组","人证核验终端","阅读器"]}', update_by=900101 WHERE line_code='catalog-card' AND tenant_id='000000' AND del_flag='0' AND (remark IS NULL OR remark='');
UPDATE product_lines SET remark='{"src":"workbuddy-20260909-outputs","files":2,"rows":218,"model_mentions":218,"unique_models":64,"unique_customer_models":83,"subcategories":["生物识别模组","生物识别采集器"]}', update_by=900101 WHERE line_code='catalog-biometric' AND tenant_id='000000' AND del_flag='0' AND (remark IS NULL OR remark='');
UPDATE product_lines SET remark='{"src":"workbuddy-20260909-outputs","files":2,"rows":150,"model_mentions":150,"unique_models":53,"unique_customer_models":123,"subcategories":["充值机","消费机"]}', update_by=900101 WHERE line_code='catalog-consumer' AND tenant_id='000000' AND del_flag='0' AND (remark IS NULL OR remark='');
UPDATE product_lines SET remark='{"src":"workbuddy-20260909-outputs","files":9,"rows":140,"model_mentions":140,"unique_models":34,"unique_customer_models":39,"subcategories":["探测立柱","测温产品","液体检测","爆炸毒品检测","路障产品","车检产品","金属检测机","防爆产品","鞋底检测"]}', update_by=900101 WHERE line_code='catalog-inspection' AND tenant_id='000000' AND del_flag='0' AND (remark IS NULL OR remark='');
UPDATE product_lines SET remark='{"src":"workbuddy-20260909-outputs","files":3,"rows":76,"model_mentions":76,"unique_models":53,"unique_customer_models":55,"subcategories":["储能产品","光伏","逆变器"]}', update_by=900101 WHERE line_code='catalog-energy' AND tenant_id='000000' AND del_flag='0' AND (remark IS NULL OR remark='');
UPDATE product_lines SET remark='{"src":"workbuddy-20260909-outputs","files":1,"rows":15,"model_mentions":15,"unique_models":12,"unique_customer_models":8,"subcategories":["储物柜"]}', update_by=900101 WHERE line_code='catalog-commercial' AND tenant_id='000000' AND del_flag='0' AND (remark IS NULL OR remark='');
UPDATE product_lines SET remark='{"src":"checklist-583","unique_models":54,"subcategories":["人证核验产品","身份证阅读机具","生物识别采集器","生物识别模组"],"note":"应建清单单独产品线，不并入证卡产品"}', update_by=900101 WHERE line_code='catalog-idcard' AND tenant_id='000000' AND del_flag='0' AND (remark IS NULL OR remark='');
