package org.ruoyi.ipd.agent.kernel;
import io.agentscope.core.state.*;import io.agentscope.core.agent.*;import io.agentscope.core.message.*;import io.agentscope.core.model.*;import io.agentscope.core.permission.*;import io.agentscope.core.tool.*;import io.agentscope.harness.agent.*;import org.redisson.*;import org.redisson.config.*;import org.ruoyi.chat.kernel.*;import java.util.*;import java.nio.file.*;import java.util.concurrent.atomic.*;import java.util.function.*;import reactor.core.publisher.*;import static org.mockito.Mockito.*;
public class GRedisPausedCleanupProbe {
 static void producer(AgentStateStore store,Path path,String user,String session){var toolkit=new Toolkit();toolkit.registerAgentTool(new ToolBase(ToolBase.builder().name("owned_probe").description("synthetic").inputSchema(Map.of("type","object"))){public Mono<ToolResultBlock>callAsync(ToolCallParam p){throw new AssertionError("must pause");}});Model model=new Model(){public String getModelName(){return "stub";}public Flux<ChatResponse>stream(List<Msg>m,List<ToolSchema>t,GenerateOptions o){return Flux.just(ChatResponse.builder().id("synthetic").content(List.of(ToolUseBlock.builder().id("pending").name("owned_probe").input(Map.of()).content("{}").build())).finishReason("tool_calls").build());}};try(var agent=HarnessAgent.builder().name("redis-paused-probe").workspace(path).model(model).toolkit(toolkit).stateStore(store).permissionContext(PermissionContextState.builder().addAskRule("owned_probe",new PermissionRule("owned_probe",null,PermissionBehavior.ASK,"synthetic")).build()).build()){agent.streamEvents(Msg.builder().role(MsgRole.USER).textContent("synthetic").build(),RuntimeContext.builder().userId(user).sessionId(session).build()).collectList().block();}}
 public static void main(String[]a){String owned=UUID.randomUUID().toString();String prefix="ipd:qa:g-cleanup:"+owned+":";String user="qa-user-"+owned,root="qa-run-"+owned,child=root+"/official/"+UUID.randomUUID(),other="qa-other-"+owned;var config=new Config();var single=config.useSingleServer().setAddress("redis://127.0.0.1:"+System.getenv("G_OWNED_REDIS_PORT")).setConnectTimeout(2000).setTimeout(2000).setConnectionMinimumIdleSize(1).setConnectionPoolSize(2).setSubscriptionConnectionMinimumIdleSize(1).setSubscriptionConnectionPoolSize(2);String auth=System.getenv("G_OWNED_REDIS_AUTH");if(auth!=null&&!auth.isEmpty())single.setPassword(auth);var client=Redisson.create(config);var store=AgentScopeRedisStateStores.create(client,prefix);try {
 producer(store,Path.of(a[0]).resolve("root"),user,root);producer(store,Path.of(a[0]).resolve("child"),user,child);store.save(user,other,"agent_state",AgentState.builder().userId(user).sessionId(other).build());if(!store.exists(user,root)||!store.exists(user,child)||!store.exists(user,other))throw new AssertionError("fixture not saved");System.out.println("REAL_SDK_ROOT_AND_OFFICIAL_NAMESPACE_PAUSED_SAVED=PASS");
 var owner=mock(ProjectAgentEventSink.class);var held=new AtomicBoolean(true);doAnswer(i->{if(!held.get())throw new IllegalStateException("synthetic owner lost");return ((Supplier<?>)i.getArgument(0)).get();}).when(owner).withActiveOwnership(any());var spec=new ProjectAgentRunSpec(1L,2L,"t",3L,null,"synthetic",List.of(),List.of(),new KernelModelRequest("stub","stub","synthetic","https://synthetic.example"),null);var access=new ProjectAgentRuntimeAccessSink(owner,spec,s->{throw new IllegalStateException("synthetic ACL withdrawn");});boolean aclDenied=false;try{access.requireActiveOwnership();}catch(IllegalStateException expected){aclDenied=true;}if(!aclDenied)throw new AssertionError("ACL not denied");Runnable cleanup=()->{for(String session:store.listSessionIds(user))if(session.equals(root)||session.startsWith(root+"/official/"))store.delete(user,session);store.delete(user,root);};access.checkpointOwnership().withActiveOwnership(()->{cleanup.run();return null;});if(store.exists(user,root)||store.exists(user,child)||!store.exists(user,other))throw new AssertionError("namespace cleanup mismatch");System.out.println("ACL_WITHDRAWN_RUN_OWNER_CLEANUP_ROOT_CHILD_ONLY=PASS");
 store.save(user,root,"agent_state",AgentState.builder().userId(user).sessionId(root).build());held.set(false);boolean ownerDenied=false;try{access.checkpointOwnership().withActiveOwnership(()->{cleanup.run();return null;});}catch(IllegalStateException expected){ownerDenied=true;}if(!ownerDenied||!store.exists(user,root))throw new AssertionError("lost owner deleted");System.out.println("LOST_RUN_OWNER_CANNOT_CLEAN=PASS");
 }finally {long deleted=client.getKeys().deleteByPattern(prefix+"*");System.out.println("OWNED_UUID_NAMESPACE_FINAL_CLEANUP_KEYS="+deleted);store.close();client.shutdown();}}
}
