package org.ruoyi.ipd.agent.service;
import java.util.*;import java.util.concurrent.atomic.*;import org.ruoyi.ipd.agent.store.*;import org.ruoyi.ipd.agent.domain.*;import org.ruoyi.ipd.agent.model.*;import org.springframework.transaction.support.*;import org.springframework.transaction.TransactionDefinition;import static org.mockito.Mockito.*;import static org.mockito.ArgumentMatchers.*;
public class GCommitProbe {
 static void check(boolean b,String m){if(!b)throw new AssertionError(m);}
 public static void main(String[]args){for(String mode:List.of("success","commitfail","cleanupfail","leaselost","outerrollback")){
 var run=IpdAgentRun.builder().id(777L).tenantId("t").personId(7L).projectId(9L).status("RUNNING").build();var store=mock(AgentRunStore.class);var events=new ArrayList<IpdAgentRunEvent>();when(store.findRun(any())).thenAnswer(i->Optional.of(run));when(store.lockEpoch(any(),anyInt())).thenReturn(true);when(store.maxSeq(any())).thenAnswer(i->(long)events.size());when(store.terminalSeq(any())).thenAnswer(i->events.isEmpty()?Optional.empty():Optional.of((long)events.size()));when(store.appendEvent(any())).thenAnswer(i->{events.add(i.getArgument(0));return true;});when(store.transition(any(),any(),any(),any(),any())).thenAnswer(i->{run.setStatus(((AgentRunStatus)i.getArgument(2)).name());return true;});
 var held=new AtomicBoolean(true);var receipts=new AtomicInteger();var cleanup=new AtomicInteger();var closed=new AtomicInteger();var commits=new AtomicInteger();var active=new AtomicBoolean();var log=new ArrayList<String>();
 var manager=new AbstractPlatformTransactionManager(){protected Object doGetTransaction(){return active;}protected boolean isExistingTransaction(Object t){return active.get();}protected void doBegin(Object t,TransactionDefinition d){active.set(true);}protected void doCommit(DefaultTransactionStatus st){if(mode.equals("commitfail"))throw new IllegalStateException("commitfailure");commits.incrementAndGet();active.set(false);if(mode.equals("leaselost"))held.set(false);}protected void doRollback(DefaultTransactionStatus st){run.setStatus("RUNNING");events.clear();active.set(false);}protected void doSetRollbackOnly(DefaultTransactionStatus st){}};manager.setRollbackOnCommitFailure(true);var tx=new TransactionTemplate(manager);
 var h=new ProjectAgentRunHandle(run,store,new com.fasterxml.jackson.databind.ObjectMapper(),()->1000L,()->{closed.incrementAndGet();held.set(false);});h.onText("无业务变更的测试正文");h.setFinishTransaction(tx);h.setOwnership(new ProjectAgentRunOwnership.Lease(){public boolean held(){return held.get();}public long token(){return 1;}public void close(){held.set(false);}},1);
 h.registerTerminalSuccessReceipt(()->{receipts.incrementAndGet();log.add("receipt:commits="+commits+":active="+active);});h.registerTemporaryStateCleanup(()->{cleanup.incrementAndGet();if(mode.equals("cleanupfail"))throw new IllegalStateException("cleanupfailure");});
 if(mode.equals("outerrollback")){try{tx.executeWithoutResult(st->{h.onComplete();throw new IllegalStateException("outerrollback");});}catch(IllegalStateException expected){}check(receipts.get()==1&&cleanup.get()==1&&commits.get()==0&&run.getStatus().equals("RUNNING"),"outer counterexample");}
 else {h.onComplete();System.out.println("DEBUG="+mode+" r="+receipts+" c="+cleanup+" status="+run.getStatus()+" commits="+commits+" events="+events.size());if(mode.equals("commitfail"))check(receipts.get()==0&&cleanup.get()==0&&run.getStatus().equals("RUNNING")&&closed.get()==0,"commitfail retains");else if(mode.equals("leaselost"))check(receipts.get()==0&&cleanup.get()==0&&run.getStatus().equals("SUCCEEDED"),"lost lease retain");else check(receipts.get()==1&&cleanup.get()==1&&run.getStatus().equals("SUCCEEDED")&&commits.get()==1,"committed");}
 System.out.println("CASE="+mode+" receipts="+receipts+" cleanup="+cleanup+" commits="+commits+" status="+run.getStatus()+" closed="+closed+" log="+log);
 }} }
