package org.ruoyi.ipd.agent.service;
import java.util.*;import java.util.concurrent.atomic.*;import org.ruoyi.ipd.agent.store.*;import org.ruoyi.ipd.agent.domain.*;import org.ruoyi.ipd.agent.model.*;import org.springframework.transaction.support.*;import org.springframework.transaction.TransactionDefinition;import static org.mockito.Mockito.*;import static org.mockito.ArgumentMatchers.*;
public class GRequiresNewProbe {
 static void check(boolean b,String m){if(!b)throw new AssertionError(m);}
 public static void main(String[]args){for(String mode:List.of("success","commitfail","cleanupfail","leaselost","outerrollback","nosuspend")){
 var run=IpdAgentRun.builder().id(777L).tenantId("t").personId(7L).projectId(9L).status("RUNNING").build();var store=mock(AgentRunStore.class);var events=new ArrayList<IpdAgentRunEvent>();when(store.findRun(any())).thenAnswer(i->Optional.of(run));when(store.lockEpoch(any(),anyInt())).thenReturn(true);when(store.maxSeq(any())).thenAnswer(i->(long)events.size());when(store.terminalSeq(any())).thenAnswer(i->events.isEmpty()?Optional.empty():Optional.of((long)events.size()));when(store.appendEvent(any())).thenAnswer(i->{events.add(i.getArgument(0));return true;});when(store.transition(any(),any(),any(),any(),any())).thenAnswer(i->{run.setStatus(((AgentRunStatus)i.getArgument(2)).name());return true;});
 var held=new AtomicBoolean(true);var receipts=new AtomicInteger();var cleanup=new AtomicInteger();var closed=new AtomicInteger();var commits=new AtomicInteger();var active=new AtomicBoolean();var log=new ArrayList<String>();
 var current=new ThreadLocal<Object[]>();var suspends=new AtomicInteger();var resumes=new AtomicInteger();
 var manager=new AbstractPlatformTransactionManager(){protected Object doGetTransaction(){return new Object[]{current.get()};}protected boolean isExistingTransaction(Object t){return ((Object[])t)[0]!=null;}protected void doBegin(Object t,TransactionDefinition d){var frame=new Object[]{run.getStatus(),new ArrayList<>(events),commits.get()};((Object[])t)[0]=frame;current.set(frame);active.set(true);}protected Object doSuspend(Object t){if(mode.equals("nosuspend"))throw new org.springframework.transaction.TransactionSuspensionNotSupportedException("no suspension");var frame=((Object[])t)[0];((Object[])t)[0]=null;current.remove();active.set(false);suspends.incrementAndGet();return frame;}protected void doResume(Object t,Object suspended){((Object[])t)[0]=suspended;current.set((Object[])suspended);active.set(true);resumes.incrementAndGet();}protected void doCommit(DefaultTransactionStatus st){if(mode.equals("commitfail"))throw new IllegalStateException("commitfailure");commits.incrementAndGet();if(mode.equals("leaselost"))held.set(false);}protected void doRollback(DefaultTransactionStatus st){var frame=(Object[])((Object[])st.getTransaction())[0];if(commits.get()==(Integer)frame[2]){run.setStatus((String)frame[0]);events.clear();events.addAll((List<IpdAgentRunEvent>)frame[1]);}}protected void doCleanupAfterCompletion(Object t){current.remove();active.set(false);}protected void doSetRollbackOnly(DefaultTransactionStatus st){}};manager.setRollbackOnCommitFailure(true);var tx=new TransactionTemplate(manager);
 var h=new ProjectAgentRunHandle(run,store,new com.fasterxml.jackson.databind.ObjectMapper(),()->1000L,()->{closed.incrementAndGet();held.set(false);});h.onText("无业务变更的测试正文");h.setFinishTransaction(tx);h.setOwnership(new ProjectAgentRunOwnership.Lease(){public boolean held(){return held.get();}public long token(){return 1;}public void close(){held.set(false);}},1);
 h.registerTerminalSuccessReceipt(()->{receipts.incrementAndGet();log.add("receipt:commits="+commits+":active="+active);});h.registerTemporaryStateCleanup(()->{cleanup.incrementAndGet();if(mode.equals("cleanupfail"))throw new IllegalStateException("cleanupfailure");});
 if((mode.equals("outerrollback")||mode.equals("nosuspend"))){try{tx.executeWithoutResult(st->{h.onComplete();throw new IllegalStateException("outerrollback");});}catch(IllegalStateException expected){}if(mode.equals("nosuspend"))check(receipts.get()==0&&cleanup.get()==0&&commits.get()==0&&run.getStatus().equals("RUNNING")&&closed.get()==0,"unsupported suspension failclosed");else check(receipts.get()==1&&cleanup.get()==1&&commits.get()==1&&run.getStatus().equals("SUCCEEDED")&&suspends.get()==1&&resumes.get()==1,"independent commit survives outerrollback");}
 else {h.onComplete();System.out.println("DEBUG="+mode+" r="+receipts+" c="+cleanup+" status="+run.getStatus()+" commits="+commits+" events="+events.size());if(mode.equals("commitfail"))check(receipts.get()==0&&cleanup.get()==0&&run.getStatus().equals("RUNNING")&&closed.get()==0,"commitfail retains");else if(mode.equals("leaselost"))check(receipts.get()==0&&cleanup.get()==0&&run.getStatus().equals("SUCCEEDED"),"lost lease retain");else check(receipts.get()==1&&cleanup.get()==1&&run.getStatus().equals("SUCCEEDED")&&commits.get()==1,"committed");}
 System.out.println("CASE="+mode+" receipts="+receipts+" cleanup="+cleanup+" commits="+commits+" status="+run.getStatus()+" closed="+closed+" suspends="+suspends+" resumes="+resumes+" log="+log);
 }} }
