package org.ruoyi.ipd.agent.service;
import org.ruoyi.ipd.agent.support.*;import org.ruoyi.ipd.agent.domain.*;import org.ruoyi.ipd.agent.model.*;import org.ruoyi.ipd.agent.kernel.*;import org.ruoyi.chat.kernel.*;import org.springframework.transaction.*;import org.springframework.transaction.support.*;import reactor.core.scheduler.*;import reactor.core.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;import com.fasterxml.jackson.databind.*;import static org.mockito.Mockito.*;
public class GResumeExecutorConsumerProbe{
 static Object field(Object x,String n)throws Exception{var f=x.getClass().getDeclaredField(n);f.setAccessible(true);return f.get(x);}
 static void run(String kind)throws Exception{
 var f=new ProjectAgentAguiPauseResumeServiceTest();var store=(InMemoryAgentRunStore)field(f,"store");var old=(ProjectAgentRunHandle)field(f,"handle");var service=(ProjectAgentAguiPauseResumeService)field(f,"service");var pending=f.getClass().getDeclaredMethod("pending");pending.setAccessible(true);service.pause(old,42L,3,(Map<String,io.agentscope.core.agui.event.AguiEvent.Interrupt>)pending.invoke(f));var run=store.findRun(42L).orElseThrow();
 var cleanup=new AtomicInteger();var calls=new AtomicInteger();ProjectAgentKernel kernel=(spec,sink)->{calls.incrementAndGet();if(!"RUNNING".equals(store.findRun(42L).orElseThrow().getStatus()))throw new AssertionError("kernel before CAS");return ()->{};};var scheduler=mock(Scheduler.class);when(scheduler.schedule(any())).thenAnswer(i->{if(kind.equals("scheduleReject"))throw new RejectedExecutionException("synthetic");((Runnable)i.getArgument(0)).run();return (Disposable)()->{};});when(scheduler.schedulePeriodically(any(),anyLong(),anyLong(),any())).thenReturn((Disposable)()->{});
 var executor=new ProjectAgentRunExecutor(store,null,kernel,new ObjectMapper(),scheduler,()->2000L,1);var tx=mock(PlatformTransactionManager.class);when(tx.getTransaction(any())).thenAnswer(i->new SimpleTransactionStatus());executor.setFinishTransaction(new TransactionTemplate(tx));var owner=mock(ProjectAgentRunOwnership.class);var lease=mock(ProjectAgentRunOwnership.Lease.class);when(lease.held()).thenReturn(true);when(owner.acquire(42L)).thenReturn(Optional.of(lease));executor.setOwnership(owner);executor.setAguiPauseResume(service);executor.setPausedCheckpointCleanup(rn->cleanup.incrementAndGet());
 if(kind.equals("detachedCancel")){store.transition(42L,Set.of(AgentRunStatus.WAITING_APPROVAL),AgentRunStatus.CANCEL_REQUESTED,null,new Date());run=store.findRun(42L).orElseThrow();if(!executor.finishDetachedCancellation(run))throw new AssertionError("cancel not finished");if(!"CANCELLED".equals(store.findRun(42L).orElseThrow().getStatus())||cleanup.get()!=1||calls.get()!=0)throw new AssertionError("cancel contract");System.out.println(kind+"=PASS");return;}
 boolean failed=false;try{executor.resumePrepared(run,h->{if(kind.equals("validationFailure"))throw new IllegalArgumentException("synthetic invalid");if(!store.transition(42L,Set.of(AgentRunStatus.WAITING_APPROVAL),AgentRunStatus.RUNNING,null,new Date()))throw new AssertionError("resume CAS");h.onStep("AGUI_RESUMED",Map.of("pauseSeq",1));return new ProjectAgentRunSpec(42L,9L,"t",7L,"C02","synthetic",List.of(),List.of(),new KernelModelRequest("stub","stub","synthetic","https://synthetic.example"),null,null,null,null,null,List.of(io.agentscope.core.message.Msg.builder().role(io.agentscope.core.message.MsgRole.USER).textContent("synthetic decision").build()));});}catch(RuntimeException expected){failed=true;}
 var status=store.findRun(42L).orElseThrow().getStatus();if(kind.equals("validationFailure")){if(!failed||!"WAITING_APPROVAL".equals(status)||cleanup.get()!=0||calls.get()!=0||executor.handle(42L).isPresent()||!executor.tryReserve())throw new AssertionError("validation failure boundary");}
 else if(kind.equals("scheduleReject")){if(!failed||!"FAILED".equals(status)||cleanup.get()!=1||calls.get()!=0||executor.handle(42L).isPresent()||!executor.tryReserve())throw new AssertionError("schedule reject boundary");}
 else {if(failed||!"RUNNING".equals(status)||calls.get()!=1||executor.tryReserve())throw new AssertionError("resume contract");var events=store.listEvents(42L,0,200);if(events.stream().anyMatch(e->"RUN_STARTED".equals(e.getEventType())||e.getPayload().contains("INTENT")))throw new AssertionError("duplicate new start");}
 if(kind.equals("resumeSuccess")){var firstHandle=executor.handle(42L).orElseThrow();firstHandle.onAguiInterrupt((Map<String,io.agentscope.core.agui.event.AguiEvent.Interrupt>)pending.invoke(f),4);if(executor.handle(42L).isPresent())throw new AssertionError("old handle not released");executor.resumePrepared(store.findRun(42L).orElseThrow(),h->{store.transition(42L,Set.of(AgentRunStatus.WAITING_APPROVAL),AgentRunStatus.RUNNING,null,new Date());return new ProjectAgentRunSpec(42L,9L,"t",7L,"C02","synthetic",List.of(),List.of(),new KernelModelRequest("stub","stub","synthetic","https://synthetic.example"),null,null,null,null,null,List.of(io.agentscope.core.message.Msg.builder().role(io.agentscope.core.message.MsgRole.USER).textContent("synthetic decision").build()));});var newHandle=executor.handle(42L).orElseThrow();firstHandle.abandonOwnership();firstHandle.cancel();if(executor.handle(42L).orElseThrow()!=newHandle||executor.tryReserve())throw new AssertionError("old callback released new handle/quota");System.out.println("staleOldHandleDoesNotReleaseNewHandle=PASS");}
 System.out.println(kind+"=PASS epoch="+store.findRun(42L).orElseThrow().getVersion()+" cleanup="+cleanup.get());}
 public static void main(String[]a)throws Exception{for(String x:List.of("resumeSuccess","validationFailure","scheduleReject","detachedCancel"))run(x);}}
