package org.ruoyi.ipd.agent.service;
import java.util.*;import java.util.concurrent.atomic.*;import static org.mockito.Mockito.*;
public class GPauseHandleLifecycleProbe {
 static Object field(Object x,String name)throws Exception {var f=x.getClass().getDeclaredField(name);f.setAccessible(true);return f.get(x);}
 public static void main(String[]a)throws Exception{
  var fixture=new ProjectAgentAguiPauseResumeServiceTest();var handle=(ProjectAgentRunHandle)field(fixture,"handle");var service=(ProjectAgentAguiPauseResumeService)field(fixture,"service");var pending=fixture.getClass().getDeclaredMethod("pending");pending.setAccessible(true);var interrupts=(Map<String,io.agentscope.core.agui.event.AguiEvent.Interrupt>)pending.invoke(fixture);
  var cleanup=new AtomicInteger();var subscription=mock(reactor.core.Disposable.class);handle.attach(subscription);handle.registerTemporaryStateCleanup(cleanup::incrementAndGet);handle.setAguiInterruptHandler((p,v)->{service.pause(handle,42L,v,p);if(handle.isPaused())throw new AssertionError("paused before commit callback returned");verify(subscription,never()).dispose();});handle.onAguiInterrupt(interrupts,3);if(!handle.isPaused()||!handle.isClosed())throw new AssertionError("pause flags missing");verify(subscription,times(1)).dispose();handle.releaseTemporaryState();if(cleanup.get()!=0)throw new AssertionError("paused checkpoint deleted");System.out.println("SUCCESS_PAUSE_FLAGS_DISPOSE_AND_KEEP=PASS");System.out.println("PAUSED_HANDLE_CANCEL_RESULT="+handle.cancel());System.out.println("PAUSED_CANCEL_CHECKPOINT_CLEANUPS="+cleanup.get());
  var second=new ProjectAgentAguiPauseResumeServiceTest();var failed=(ProjectAgentRunHandle)field(second,"handle");var failedSubscription=mock(reactor.core.Disposable.class);failed.attach(failedSubscription);failed.setAguiInterruptHandler((p,v)->{throw new IllegalStateException("synthetic commit failure");});boolean rejected=false;try{failed.onAguiInterrupt(interrupts,3);}catch(IllegalStateException expected){rejected=true;}if(!rejected||failed.isClosed()||failed.isPaused())throw new AssertionError("failure released handle");verify(failedSubscription,never()).dispose();System.out.println("HANDLER_FAILURE_NO_RELEASE=PASS");
 }
}
